/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind;

/**
 *
 * @author matth
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_grille = new javax.swing.JPanel();
        pan_infojoueur = new javax.swing.JPanel();
        pan_partie = new javax.swing.JPanel();
        pan_jeton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan_grille.setBackground(new java.awt.Color(204, 102, 0));
        pan_grille.setLayout(new java.awt.GridLayout(12, 4));
        getContentPane().add(pan_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 384, 768));

        pan_infojoueur.setBackground(new java.awt.Color(102, 255, 102));
        pan_infojoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pan_infojoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 280, 110));

        pan_partie.setBackground(new java.awt.Color(102, 255, 102));
        pan_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pan_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 280, 130));

        pan_jeton.setBackground(new java.awt.Color(102, 255, 102));
        pan_jeton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pan_jeton.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        getContentPane().add(pan_jeton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 280, 130));

        setBounds(0, 0, 1034, 842);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pan_grille;
    private javax.swing.JPanel pan_infojoueur;
    private javax.swing.JPanel pan_jeton;
    private javax.swing.JPanel pan_partie;
    // End of variables declaration//GEN-END:variables
}
